from typing import Any, Protocol


class ValueType(Protocol):
    def __add__(self, other: Any, /) -> Any: ...
    def __sub__(self, other: Any, /) -> Any: ...
    def __mul__(self, other: Any, /) -> Any: ...
    def __truediv__(self, other: Any, /) -> Any: ...
    def __pow__(self, other: Any, /) -> Any: ...
    def __radd__(self, other: Any, /) -> Any: ...
    def __rsub__(self, other: Any, /) -> Any: ...
    def __rmul__(self, other: Any, /) -> Any: ...
    def __rtruediv__(self, other: Any, /) -> Any: ...
    def __eq__(self, other: Any, /) -> Any: ...
    def __lt__(self, other: Any, /) -> Any: ...
